### ISSUE TITLE
Must enter password in command line

### ISSUE THREAD

**Issue by dbns97** [electricimp/imp-central-impt#14]
To authenticate when using `impt auth` the user has to enter their password into the command line which isn't great because it's then stored in the shell's history. It would be nice if when the user calls `impt auth` without providing a password it prompts them to enter the password with stdin so that the password isn't then stored. `htpasswd` is a good example.

**Comment by ppetrosh** [comment]
Thanks Drew. This makes total sense to me. For now I would recommend using loginkeys (`-lk`) instead, which might make it a little bit less scary.

**Comment by dbns97** [comment]
Hey Pavel, you're right and I do plan on using login keys but the password is required for creating the keys in the first instance.

**Comment by ppetrosh** [comment]
That's true, yes.

**Comment by rlipscombe** [comment]
Or if the password could be taken from a file: `--pwdfile` or something?

**Comment by ppetrosh** [comment]
Yes, that's also an option, agree. However, I would prefer the type-in way.

**Comment by thomaskoehn-kisi** [comment]
+1. I'd also prefer to have the regular password prompt that keeps the password out of the history. thanks!

**Comment by alexey-nbl** [comment]
The proposed change for "impt auth login" command:

Either "--user <user_id>" or "--lk <login_key_id>" option must be specified.

When "--user" option is specified:
- if "--pwd <password>" option is specified as well, it is considered as a password.
- if "--pwd" option is not specified, the tool prompts "Enter password>" and waits for an input.

**Comment by ppetrosh** [comment]
Agree, I believe that should be sufficient.

**Comment by ppetrosh** [comment]
Fixed.
