### ISSUE TITLE
If output is not to a terminal, drop the colours

### ISSUE THREAD

**Issue by rlipscombe** [electricimp/imp-central-impt#15]
With the ANSI colour escapes, I can't use grep, cut, etc. to chop up the output.

**Comment by ppetrosh** [comment]
That's a good point. Thanks! Will add this to the backlog.

**Comment by alexey-nbl** [comment]
An idea is to introduce new group of commands - "impt setup" - with commands which control the tool behavior/output.
One of the commands, for example, would switch on/off "script" mode - a mode where meaningful output is formatted as json, other output and colors are off, etc.

**Comment by rlipscombe** [comment]
See my comments on #16.

**Comment by ppetrosh** [comment]
This seems to be fixed already...
