### ISSUE TITLE
`impt test run` does not log assert messages

### ISSUE THREAD

**Issue by deldrid1** [electricimp/imp-central-impt#25]
Take the following code:

```squirrel
@include once "lib/deep-object-diff/deepDiff.nut"

class DeepDiffTestCase extends ImpTestCase {
    // ...
    // Lots of test functions
    // ...
     
    function testRecursiveArrays(){
    
        // ...
        // Lots of asserts
        // ...  

        this.assertDeepEqual(
           diff([1, 2, 3], [9, 8, 3]),
           { [0]= 9, [1]= 8 },
           "returns subset of right hand side array as object of indices to value when arrays differs at multiple indicies"
        )

        // ...
        // Lots of additional asserts
        // ...  

    }

    // ...
    // Lots of test functions
    // ...
}
```

In the case that this assert is failing, I get the following output
```bash
[+10.29/0.00s test] DeepDiffTestCase::testRecursiveArrays()
[+10.29/0.00s test] Failure: Missing slot [0.1.2] in actual value
```

While this log is useful for debugging once I know which actual assert that is the culprit, I have loads of asserts in this test function.  In order to find the one that was the issue I had to manually comment out the different asserts one at a time and rerun the tests.  This is because the nice message that I had provided my assert isn't being logged anywhere....

I'm not sure if this is an impt issue or rather an impUnit or impTest issue but regardless, can it be fixed @ppetrosh?

**Comment by ppetrosh** [comment]
Yes, I believe it's an `impt test` issue. Will take care of this. Thanks, @deldrid1

**Comment by deldrid1** [comment]
Thanks Pavel.

One more "nice to have" along this same topic would be if `impt` would summarize **all** test results after the final test script has ran so you didn't have to go chasing through the output to find any failures.  i.e. something like

```bash
----------TEST RESULTS-------------
[+26.23/0.00s test] Tests: 52, Assertions: 164, Failures: 3
[]
[+25.71/0.00s test] Failure 1 - DeepUpdatedDiffTestCase::testBaseInEqualityCase()
[+25.71/0.00s test] Failure: the index 'hasOwnProperty' does not exist (line 103)
...
```

**Comment by ppetrosh** [comment]
Agree, this makes sense too.
