### ISSUE TITLE
Errors during build aren't reported fully when output is json

### ISSUE THREAD

**Issue by blindman2k** [electricimp/imp-central-impt#91]
When there is a compilation error during an "impt build" command with the default output, the response is something like this.

```
Error: Compilation Error: There was an error with compilation.
agent_code error (line 2886, column 51): expected 'IDENTIFIER'
IMPT COMMAND FAILS
```

When the same error appears with the json output, the response is this:

```
{
  "Error": "Compilation Error: There was an error with compilation."
}
```

It would be really valuable to have the entire error message in the json output, even if it is in a new field.

**Comment by teenujose1** [comment]
Issue is resolved in IMPT published version 2.6.0
